# Generated by Django 3.0.1 on 2019-12-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0002_auto_20191227_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', upload_to='lgs/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
