# Generated by Django 3.0.1 on 2020-01-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactdb',
        ),
    ]
