# Generated by Django 3.0.1 on 2020-01-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0005_auto_20200122_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderfromwebsite',
            fields=[
                ('price', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdb',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
