# Generated by Django 3.0.1 on 2020-01-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0006_auto_20200124_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
