# Generated by Django 3.0.2 on 2020-01-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0008_auto_20200129_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='after_payment',
            fields=[
                ('orderid', models.CharField(max_length=50)),
                ('transaction_amount', models.FloatField(primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=50)),
                ('response_message', models.CharField(max_length=50)),
                ('bank_transaction_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('checksum', models.CharField(default='checksum not gone for verification', max_length=50)),
            ],
        ),
    ]
