# Generated by Django 3.0.2 on 2020-01-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0009_after_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after_payment',
            name='bank_transaction_id',
            field=models.CharField(default='NOT GENERATED', max_length=50),
        ),
    ]
