# Generated by Django 3.0.2 on 2020-01-28 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0011_rew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rew',
        ),
    ]
