# Generated by Django 3.0.2 on 2020-01-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0012_delete_rew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='after_payment',
            name='orderid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='transaction_amount',
            field=models.FloatField(),
        ),
    ]
