# Generated by Django 3.0.2 on 2020-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0013_auto_20200129_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfromwebsite',
            name='goods_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orderfromwebsite',
            name='goods_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderfromwebsite',
            name='goods_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
