# Generated by Django 3.0.2 on 2020-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0015_auto_20200129_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='goods_amount',
            field=models.CharField(max_length=50),
        ),
    ]
