# Generated by Django 3.0.2 on 2020-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0018_auto_20200129_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='goods_amount',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='goods_count',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='goods_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
