# Generated by Django 3.0.2 on 2020-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0019_auto_20200129_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='after_payment',
            name='transaction_date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='bank_transaction_id',
            field=models.CharField(default='NOT GENERATED', max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='checksum',
            field=models.CharField(default='checksum not gone for verification', max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='currency',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='orderid',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='response_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='response_message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='after_payment',
            name='transaction_id',
            field=models.CharField(max_length=500),
        ),
    ]
