# Generated by Django 3.0.2 on 2020-01-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0022_auto_20200129_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfromwebsite',
            name='orderId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
