# Generated by Django 3.0.2 on 2020-01-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0023_auto_20200129_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderfromwebsite',
        ),
    ]
