# Generated by Django 3.0.2 on 2020-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0024_delete_orderfromwebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderfromwebsite',
            fields=[
                ('goods_count', models.CharField(max_length=500, null=True)),
                ('goods_name', models.CharField(max_length=500, null=True)),
                ('goods_amount', models.CharField(max_length=500, null=True)),
                ('price', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('local', models.CharField(max_length=500)),
                ('orderId', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
    ]
