# Generated by Django 3.0.2 on 2020-02-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgs', '0025_orderfromwebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orederid', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=500)),
            ],
        ),
    ]
